### ISSUE TITLE
How I can create a server?

### ISSUE THREAD

**Issue by TheDesertRoad** [Fox2Code/FoxLoader#1]

**Comment by Fox2Code** [comment]
`java -jar FoxLoader.jar --server` honestly, I'm not sure how to tell you.

What you told me is of real concern, I tried to be as clear as possible.

You can go here https://discord.gg/38Vfes6NpR if you want faster responses.

**Comment by SpikeHD** [comment]
I would highly recommend putting common use-cases directly in the README, I see no mention of how to launch this as a server within it. Most people use READMEs as a single (or first, at the very least) point of contact for documentation, as much as we'd all love for people to try `--help` options first :P.

**Comment by Fox2Code** [comment]
@SpikeHD thank for the feedback, I updated the readme!

Should be good enough!
