### ISSUE TITLE
Request: a beforeWorldStop method

### ISSUE THREAD

**Issue by DudeSquaredEdud** [Fox2Code/FoxLoader#10]
Hey Fox,

I'm trying to implement a method that corrects the player's position before the server closes (crouching changes the player's yOffset). Could you add a method that runs before everything else when the world stops / go back to title is pressed?

**Comment by Fox2Code** [comment]
@DudeSquaredEdud `onNetworkPlayerDisconnected` should work fine for it, and work on a per player basis instead of only once when entire server shutdown.

If you still think `beforeWorldStop` need to be added still, please send me a use case where it would be useful so I am sure to cover it.

**Comment by Fox2Code** [comment]
Closing issue due to lack of interest, FoxLoader 1.0 and 2.0 both contain necessary code to do what you described.
