### ISSUE TITLE
Game is suddenly crashing on startup with exit code 127 (0s7f)

### ISSUE THREAD

**Issue by KuraakaiGoro** [Fox2Code/FoxLoader#13]
The game was playing just fine, now I can't start it up without getting an exit code. I'm using MultiMC

> MultiMC version: 0.7.0-3822
> 
> 
> Launched instance in online mode
> 
> authserver.mojang.com resolves to:
>     [18.154.101.51, 18.154.101.19, 18.154.101.47, 18.154.101.93]
> 
> session.minecraft.net resolves to:
>     [2620:1ec:46::66, 2620:1ec:bdf::66, 13.107.246.66, 13.107.213.66]
> 
> textures.minecraft.net resolves to:
>     [2620:1ec:46::66, 2620:1ec:bdf::66, 13.107.213.66, 13.107.246.66]
> 
> api.mojang.com resolves to:
>     [2620:1ec:bdf::66, 2620:1ec:46::66, 13.107.213.66, 13.107.246.66]
> 
> 
> Minecraft folder is:
> /home/romu/.local/share/multimc/instances/foxloader-1.2.38-mmc/.minecraft
> 
> 
> Java path is:
> /usr/lib64/jvm/java-21-openjdk/bin/java
> 
> 
> Checking Java version...
> Java is version 21.0.2, using 64-bit architecture, from N/A.
> 
> 
> AMD Ryzen 5 5600X 6-Core Processor
> NVIDIA Corporation GA104 [GeForce RTX 3070 Ti] (rev a1)
> 
> Subsystem: Micro-Star International Co., Ltd. [MSI] GA104 [GeForce RTX 3070 Ti]
> 
> Kernel driver in use: nvidia
> 
> OpenGL version string: 4.6.0 NVIDIA 545.29.06
> 
> Main Class:
>   com.fox2code.foxloader.launcher.ClientMain
> 
> Native path:
>   /home/romu/.local/share/multimc/instances/foxloader-1.2.38-mmc/natives
> 
> Traits:
> traits texturepacks
> 
> Libraries:
>   /home/romu/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
>   /home/romu/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
>   /home/romu/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
>   /home/romu/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
>   /home/romu/.local/share/multimc/instances/foxloader-1.2.38-mmc/libraries/foxloader-1.2.38.jar
> 
> Native libraries:
>   /home/romu/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
>   /home/romu/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar
> 
> Mods:
>   [📁] ReIndev2.8.1_5 (folder)
> 
> Params:
>   Goro_Kuraakai <ACCESS TOKEN> --gameDir /home/romu/.local/share/multimc/instances/foxloader-1.2.38-mmc/.minecraft
> 
> Window size: 854 x 480
> 
> Java Arguments:
> [-XX:+IgnoreUnrecognizedVMOptions, -XX:+UnlockExperimentalVMOptions, -XX:+DisableAttachMechanism, -Dcom.ibm.tools.attach.enable=no, -Dfile.encoding=UTF-8, -XX:+UseFastAccessorMethods, -XX:+AggressiveOpts, -XX:+UseCompressedOops, -XX:+UseBiasedLocking, -XX:+OptimizeStringConcat, -XX:-UseGCOverheadLimit, -XX:+UseStringCache, -XX:+UseCompressedStrings, -Xms512m, -Xmx1024m, -Duser.language=en]
> 
> 
> Minecraft process ID: 77921
> 
> 
> Using onesix launcher.
> 
> [15:37:13] [STDOUT ] Loaded org.ow2.asm:asm:9.6 -> /home/romu/.local/share/multimc/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar
> [15:37:13] [STDOUT ] Loaded org.ow2.asm:asm-tree:9.6 -> /home/romu/.local/share/multimc/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar
> [15:37:13] [STDOUT ] Loaded org.ow2.asm:asm-analysis:9.6 -> /home/romu/.local/share/multimc/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar
> [15:37:13] [STDOUT ] Loaded org.ow2.asm:asm-commons:9.6 -> /home/romu/.local/share/multimc/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar
> [15:37:13] [STDOUT ] Loaded org.ow2.asm:asm-util:9.6 -> /home/romu/.local/share/multimc/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar
> [15:37:13] [STDOUT ] Loaded com.google.code.gson:gson:2.10.1 -> /home/romu/.local/share/multimc/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
> [15:37:13] [STDOUT ] Loaded com.google.guava:guava:21.0 -> /home/romu/.local/share/multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
> [15:37:13] [STDOUT ] Loaded org.semver4j:semver4j:5.2.2 -> /home/romu/.local/share/multimc/libraries/org/semver4j/semver4j/5.2.2/semver4j-5.2.2.jar
> [15:37:13] [STDOUT ] Loaded org.apache.commons:commons-lang3:3.3.2 -> /home/romu/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
> [15:37:13] [STDOUT ] Loaded org.luaj:luaj-jse:3.0.1 -> /home/romu/.local/share/multimc/libraries/org/luaj/luaj-jse/3.0.1/luaj-jse-3.0.1.jar
> [15:37:13] [STDOUT ] Loaded it.unimi.dsi:fastutil-core:8.5.12 -> /home/romu/.local/share/multimc/libraries/it/unimi/dsi/fastutil-core/8.5.12/fastutil-core-8.5.12.jar
> [15:37:13] [STDOUT ] Loaded net.fabricmc:sponge-mixin:0.12.5+mixin.0.8.5 -> /home/romu/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar
> [15:37:13] [STDOUT ] Loaded io.github.llamalad7:mixinextras-common:0.3.2 -> /home/romu/.local/share/multimc/libraries/io/github/llamalad7/mixinextras-common/0.3.2/mixinextras-common-0.3.2.jar
> [15:37:13] [STDOUT ] Loaded com.github.bawnorton.mixinsquared:mixinsquared-common:0.1.1 -> /home/romu/.local/share/multimc/libraries/com/github/bawnorton/mixinsquared/mixinsquared-common/0.1.1/mixinsquared-common-0.1.1.jar
> [15:37:13] [STDOUT ] Loaded com.fox2code:JFallback:0.0.2 -> /home/romu/.local/share/multimc/libraries/com/fox2code/JFallback/0.0.2/JFallback-0.0.2.jar
> [15:37:13] [STDOUT ] Loaded net.silveros:reindev:2.8.1_5 -> /home/romu/.local/share/multimc/libraries/net/silveros/reindev/2.8.1_5/reindev-2.8.1_5.jar
> [15:37:13] [INFO   ] Running FoxLoader 1.2.38
> [15:37:13] [INFO   ] Game directory: /home/romu/.local/share/multimc/instances/foxloader-1.2.38-mmc/.minecraft
> [15:37:13] [STDOUT ] Loaded maven.modrinth:spark:1.10.53-fabric -> /home/romu/.local/share/multimc/libraries/maven/modrinth/spark/1.10.53-fabric/spark-1.10.53-fabric.jar
> [15:37:13] [INFO   ] Injecting spark using FoxLoader adapter.
> [15:37:13] [INFO   ] PreLoader hash: 7B10B3C3F63C795B83BD640D646160D04FBEBCFCF6E35EBCAB31940B46600ADF
> [15:37:13] [INFO   ] Existing patched jar exists, using that!
> [15:37:13] [INFO   ] SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/romu/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=FoxMixinService Env=UNKNOWN
> [15:37:13] [INFO   ] Patched MixinConfig!
> [15:37:13] [INFO   ] Preparing mixins for MixinEnvironment[PREINIT]
> [15:37:13] [STDOUT ] Loaded mixin: foxloader.client.mixins.json
> [15:37:13] [INFO   ] Checking for additional mixins for MixinEnvironment[PREINIT]
> [15:37:13] [INFO   ] Selecting config foxloader.client.mixins.json
> [15:37:13] [INFO   ] Preparing foxloader.client.mixins.json (40)
> [15:37:13] [INFO   ] Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
> [15:37:14] [STDOUT ] Loading "en_US" lang table...
> [15:37:14] [STDOUT ] Loaded 66 loading screen tips
> [15:37:14] [STDOUT ] 473 recipes
> [15:37:14] [STDOUT ] 40 achievements
> [15:37:14] [STDOUT ] Loaded 8 commands
> [15:37:14] [STDOUT ] Loading "en_US" lang table...
> [15:37:14] [STDOUT ] Loaded 66 loading screen tips
> [15:37:14] [STDOUT ] Reloaded command: give
> [15:37:14] [STDOUT ] Reloaded command: tp
> [15:37:14] [STDOUT ] Reloaded command: help
> [15:37:14] [STDOUT ] Reloaded command: time
> [15:37:14] [STDOUT ] Reloaded command: gamemode
> [15:37:14] [STDOUT ] Reloaded command: weather
> [15:37:14] [STDOUT ] Reloaded command: clear
> [15:37:14] [STDOUT ] Reloaded command: effect
> [15:37:14] [STDOUT ] Reloaded command: /set
> [15:37:14] [STDOUT ] Reloaded command: spark
> [15:37:14] [STDOUT ] Reloaded command: tps
> [15:37:14] [STDOUT ] Reloaded command: /replace
> Process exited with exit code 127 (0x7f).
> Please note that usually neither the exit code, nor its description are enough to diagnose issues!
> Always upload the entire log and not just the exit code.
> Clipboard copy at: 10 Feb 2024 15:39:53 -0500

**Comment by KuraakaiGoro** [comment]
I found the issue, it doesn't like the latest version of Java, I switched it back to Version 18

**Comment by Fox2Code** [comment]
@KuraakaiGoro if it doesn't work with java 8 it's a bug, FoxLoader officially support any version of java from 8 to 21

**Comment by KuraakaiGoro** [comment]
> @KuraakaiGoro if it doesn't work with java 8 it's a bug, FoxLoader officially support any version of java from 8 to 21

Might be a problem with OpenJDK, then. It works fine for me now, though.
