### ISSUE TITLE
I need help:((

### ISSUE THREAD

**Issue by NgcSon** [Fox2Code/FoxLoader#15]
![Screenshot_2024-03-30-14-57-57-87_aa90cf39af1facb2c229f1c5307f0ee0](https://github.com/Fox2Code/FoxLoader/assets/94265074/ada8a56a-4827-42d4-b173-140bd0318369)
Launcher I used: PojavLauncher
Logs:
[latestlog.txt](https://github.com/Fox2Code/FoxLoader/files/14811197/latestlog.txt)

**Comment by Fox2Code** [comment]
@NgcSon please provide with the exact version of pojav launcher you are using.
