### ISSUE TITLE
FoxLoader does not load on Pebblehost (Workaround/Fix included)

### ISSUE THREAD

**Issue by tulpenkiste** [Fox2Code/FoxLoader#18]
Hi, me and my friends tried to play with FoxLoader on Pebblehost but couldn't without manually modifying the code.

This is due to the installer not recognizing "nogui"  and immediately returning in main (Pebblehost provides no way to replace this argument, hence the problem existing).

I've made a workaround to make it work which adds `nogui` and `--nogui` to the `args[0]` switch case. The diff is:
```diff
--- a/final/src/main/java/com/fox2code/foxloader/installer/Main.java
+++ b/final/src/main/java/com/fox2code/foxloader/installer/Main.java
@@ -42,6 +42,10 @@ public class Main {
                     System.out.println("--with-server -> Start server with specified server jar");
                     System.out.println("--test-server -> Like --with-server but only load the strict necessary for ");
                     return;
+                case "nogui":
+                case "--nogui":
+                    server = true;
+                    break;
                 case "--platform":
                     platform = true;
                     break;
```

**Comment by Fox2Code** [comment]
@Fox2Code I'll do that for you your code is not completely accurate, but I can adapt it

**Comment by Fox2Code** [comment]
@tulpenkiste you can check there to see how I adapted your code: https://github.com/Fox2Code/FoxLoader/commit/b20d6288b3982f5d23ead07bc44d6b89b4cb01e1

**Comment by tulpenkiste** [comment]
Looks good. :+1:
