### ISSUE TITLE
u forgot to add the jars in the latest release? (1.2.15)

### ISSUE THREAD

**Issue by AuraCatPerpinya** [Fox2Code/FoxLoader#3]
You didn't include the jar files, only the source files, in the 1.2.15 release
![imatge](https://github.com/Fox2Code/FoxLoader/assets/136636937/5906a1c8-acb9-4296-9cb2-d6eae27a8edb)

**Comment by Fox2Code** [comment]
Next time spam me on Discord, also jar takes a few minutes cause I use jitpack for releases jar.
