### ISSUE TITLE
Possibly outdated dependency on mixinextras for common?

### ISSUE THREAD

**Issue by Jade-TheCat** [Fox2Code/FoxLoader#5]
When trying to build the example mod repo (I already started work on the actual mod):

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.github.LlamaLad7.MixinExtras:mixinextras-common:0.2.0-beta.9.
     Searched in the following locations:
       - file:/home/jade/.gradle/fox-loader/com/github/LlamaLad7/MixinExtras/mixinextras-common/0.2.0-beta.9/mixinextras-common-0.2.0-beta.9.pom
       - https://repo.maven.apache.org/maven2/com/github/LlamaLad7/MixinExtras/mixinextras-common/0.2.0-beta.9/mixinextras-common-0.2.0-beta.9.pom
       - https://repo.spongepowered.org/maven/com/github/LlamaLad7/MixinExtras/mixinextras-common/0.2.0-beta.9/mixinextras-common-0.2.0-beta.9.pom
       - https://jitpack.io/com/github/LlamaLad7/MixinExtras/mixinextras-common/0.2.0-beta.9/mixinextras-common-0.2.0-beta.9.pom
       - file:/home/jade/.m2/repository/com/github/LlamaLad7/MixinExtras/mixinextras-common/0.2.0-beta.9/mixinextras-common-0.2.0-beta.9.pom
     Required by:
         project :
         project : > com.github.Fox2Code.FoxLoader:common:1.2.19
```

It appears MixinExtras 0.2.0 is out as of yesterday, so an update may be needed to correct the dependency. I don't know why it wouldn't be able to pull older versions, but maybe they removed beta.9 from Maven for some reason? It should be on Maven Central according to [the GitHub repo](https://github.com/LlamaLad7/MixinExtras). I can submit a PR tomorrow when I get a chance to fork and try to build FL.

**Comment by Fox2Code** [comment]
Thank for useful issue.

@Jade-TheCat please tell me your Minecraft username.

I might have a surprise in store.

**Comment by Jade-TheCat** [comment]
> Thank for useful issue.
> 
> @Jade-TheCat please tell me your Minecraft username.
> 
> I might have a surprise in store.

Hey, no prob! I try to do what I can for Open Source stuff like this :)

My MC is Jade_TheCat. Can't wait to see the surprise! :P

**Comment by Fox2Code** [comment]
[`1.2.20`](https://github.com/Fox2Code/FoxLoader/releases/tag/1.2.20) is finally out and updated mixin extras.
