### ISSUE TITLE
[Feature Request] Option to have a standalone server jar instead of using the installer

### ISSUE THREAD

**Issue by VanillaSylv** [Fox2Code/FoxLoader#7]
A lot of server hosters don't really support running the installer with the "--server" flag (Or anything which counts as a post-init flag), so could there possibly be a way to have a server jar with foxloader included in it instead of needing to launch the installer with the flag?

**Comment by Fox2Code** [comment]
Will work on, it! Actually the installer is the server launcher.
I'll add a button to patch the jar `META-INF/MANIFEST.MF` from the installer to help with server side installation.

**Comment by VanillaSylv** [comment]
Thank you so much, i hope this will honestly help people who depend on dedicated minecraft hosts, and would help me personally a lot <3

**Comment by Fox2Code** [comment]
<https://github.com/Fox2Code/FoxLoader/releases> Done!

Also I forgor to say that you were not the only person asking for it.

**Comment by VanillaSylv** [comment]
Thank you so much!
